In [1]:
import numpy as np

In [7]:
a1 = np.array([5,6,7])
print(a1)

[5 6 7]


In [8]:
print(a1[0])
print(a1[2])

5
7


In [9]:
# 2 dimensional array

a = np.array([[1,2],[3,4],[5,6]])
print(a.ndim) # ndim - property

2


In [6]:
print(a[0])
print(a[1,1])

[1 2]
4


In [11]:
print(a.itemsize) # integers 4 bytes long

4


In [14]:
a2 = np.array(["hello","world"])
print(a2[0])
print(a2[1])

hello
world


In [19]:
a3 = np.array(["hello",1])
print(a3) # both values are stored as strings?
print(a3.dtype)

['hello' '1']
<U11


In [20]:
print(a.size)
print(a1.size)
print(a2.size)
print(a3.size)

6
3
2
2


In [21]:
print(a.shape) # height and width

(3, 2)


In [24]:
a4 = np.array([[1,2],[3,4],[5,6]], dtype = np.float64 )
a5 = np.array([[1,2],[3,4],[5,6]], dtype = complex )

print(a4)
print(" ")
print(a5)

[[1. 2.]
 [3. 4.]
 [5. 6.]]
 
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]
 [5.+0.j 6.+0.j]]


In [25]:
# array with placeholders

a6 = np.zeros((3,4)) # argument - shape of the array
print(a6)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [26]:
l = range(5) # creates a list of given range
print(l)

range(0, 5)


In [27]:
for i in l:
    print(i)

0
1
2
3
4


In [28]:
# creating an array of given range

a = np.arange(1,5)
print(a)

[1 2 3 4]


In [29]:
a = np.arange(0,10,2)
print(a)

[0 2 4 6 8]


In [30]:
a = np.linspace(1,5,10) # creates an array of 10 numbers between 1 and 5 and it will be linearly spaced
print(a)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [31]:
a = np.linspace(1,5,5)
print(a)

[1. 2. 3. 4. 5.]


In [42]:
print(a4)
print(a4.reshape(2,3))

#print(a5)
#a5.reshape(2,4) not compatible

[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[1. 2. 3.]
 [4. 5. 6.]]


In [44]:
# flattening an array
print(a4.ravel()) # will not touch the original array
print(a4)

[1. 2. 3. 4. 5. 6.]
[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [45]:
# math functions

print(a4.min())
print(a4.max())
print(a4.sum())

1.0
6.0
21.0


In [46]:
# axis 
# axis = 0 (same column values are taken together)
# axis = 1 (same row values are taken together)

print(a4.min(axis = 0))
print(a4.max(axis = 1))
print(a4.sum(axis = 0))

[1. 2.]
[2. 4. 6.]
[ 9. 12.]


In [49]:
print(a)
print(np.sqrt(a)) # generic method

[1. 2. 3. 4. 5.]
[1.         1.41421356 1.73205081 2.         2.23606798]


In [50]:
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[5,6],[7,8]])

print(a1+a2)
print(" ")

print(a1-a2)
print(" ")

print(a1*a2) # individual elements are multiplied
print(" ")

print(a1/a2)# individual elements are divided
print(" ")


[[ 6  8]
 [10 12]]
 
[[-4 -4]
 [-4 -4]]
 
[[ 5 12]
 [21 32]]
 
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
 


In [53]:
print(a1.dot(a2)) # matrix multiplication

[[19 22]
 [43 50]]
